name: Build and Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          cd sourcecode-parser
          go mod download

      - name: Build
        run: |
          cd sourcecode-parser
          go build -o pathfinder

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: ./sourcecode-parser/pathfinder
          asset_name: pathfinder
          asset_content_type: application/octet-stream